server:
    port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/


spring:
  application:
    name: test-service
  datasource:
    url: jdbc:mysql://rm-bp1n8l70ad8b14hufo.mysql.rds.aliyuncs.com:3306/smart?useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.jdbc.Driver
    username: msmart_das_001
    password: j7Tw_TKc8 
  data:
    redis:
      repositories:
        enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
#  cloud:
#    inetutils:
#      preferred-networks: ^172.

redis:
    host: "10.117.183.80"
    port: 6379
    timeout: 5000
    password: null
    pool:
      maxTotal: 100
      maxIdle: 10
      minIdle: 1
      maxWaitMillis: 10000
      testOnBorrow: true


#国内测试接入层kafka
kafka:
  producer:
    enabled: true
    bootstrap.servers: 10.117.183.80:9092
    acks: "1"
    retries: "0"
    batch.size: "16384"
    linger.ms: "1"
    buffer.memory: "33554432"
    key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer

sys:
  http:
    maxKeepAlive: 200
    keepAliveTimeout: 23
    