server:
    port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/


spring:
  application:
    name: test-service
#  cloud:
#    inetutils:
#      preferred-networks: ^172.

    