server:
    port: 8081

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8090/eureka/

spring:
  application:
    name: test-api
#  datasource:
#    url: jdbc:mysql://rm-bp1n8l70ad8b14hufo.mysql.rds.aliyuncs.com:3306/smart?useUnicode=true&characterEncoding=UTF-8
#    driverClassName: com.mysql.jdbc.Driver
#    username: msmart_das_001
#    password: j7Tw_TKc8 
#  cloud:
#    inetutils:
#      preferred-networks: ^172.

hystrix:
  command:
    testservice-delay:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500

