# eureka服务器  peer1
spring:
  profiles: 
    active: peer1
  
server:
  port: 8090
  
eureka:
  instance:
    preferIpAddress: true
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2/eureka/
      
      
# eureka服务器  peer2
spring:
  profiles: 
    active: peer2
  
server:
  port: 8090
  
eureka:
  instance:
    preferIpAddress: true
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer3/eureka/


# eureka服务器  peer3
spring:
  profiles: 
    active: peer3
  
server:
  port: 8090
  
eureka:
  instance:
    preferIpAddress: true
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1/eureka/      